### ISSUE TITLE
17.10RC1: admin account disabled, not being able to login

### ISSUE THREAD

**Issue by gehlen** [joosth/workflow4people#39]
Login into workflow4people web interface 3 times with user "admin" and password "test", after that login one more time with the correct credentials. Message below is shown:
![image](https://user-images.githubusercontent.com/432016/33068849-d8cb85f2-ceb2-11e7-8ae1-785f2460e0fb.png)

Admin account is disabled and I'm not able to login anymore.. This is not really useful for an admin account. How am I able to login again as user "admin"? (without touching the database)

**Comment by hwinwuzhere** [comment]
This is correct behavior. When a brute-force attempt is made on the administrator account we want to block it immediately. Since we have access to the database we can reset it manually.

Perhaps a feature request for an easier recovery of the administrator account (e.g. two-factor authentication) would be an idea?
